services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:seokklee
    env_file:
      - .env
    expose:
      - "443"
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www
    networks:
      - inception
    depends_on:
      - wordpress
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:443 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    # Hostname of the container (for internal DNS)
    hostname: ${DOMAIN_NAME}
    restart: on-failure
    secrets:
      - localhost.pem
      - localhost.key
    userns_mode: "host"

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:seokklee
    env_file:
      - .env
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "cgi-fcgi", "-bind", "-connect", "localhost:9000 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    # Hostname of the container (for internal DNS)
    hostname: ${DOMAIN}
    restart: on-failure

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:seokklee
    env_file:
      - .env
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "--password=${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    # Hostname of the container (for internal DNS)
    hostname: ${DOMAIN}
    restart: on-failure:3

secrets:
  localhost.pem:
    file: ./requirements/certificate/${DOMAIN}.pem
  localhost.key:
    file: ./requirements/certificate/${DOMAIN}.key

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      o: "bind"
      type: "none"
      device: ${HOME}/data/volumes/mariadb
      # device: /var/lib/mysql

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: "none"
      device: ${HOME}/data/volumes/wordpress
      o: "bind"

  # website:
  #   name: website
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: /var/www/website
  #     o: bind
